import type { Exercise } from "./types";

// 154 pre-loaded exercises. ids are stable — workout history references them.
export const EXERCISES: Exercise[] = [
  // Chest (9)
  { id: "bench-press", name: "Barbell bench press", muscle: "chest", secondary: ["triceps", "shoulders"], equipment: "barbell", difficulty: "intermediate", instructions: "Lie on the bench, grip just outside shoulder width, lower the bar to mid-chest and press back up.", tip: "Keep your shoulder blades pinned together and feet planted." },
  { id: "incline-bench", name: "Incline barbell press", muscle: "chest", secondary: ["shoulders", "triceps"], equipment: "barbell", difficulty: "intermediate", instructions: "On a 30° incline bench, lower the bar to your upper chest and press up.", tip: "Don't let the bar drift toward your neck." },
  { id: "db-bench", name: "Dumbbell bench press", muscle: "chest", secondary: ["triceps", "shoulders"], equipment: "dumbbell", difficulty: "beginner", instructions: "Press dumbbells from chest level to lockout, palms forward.", tip: "Lower until you feel a stretch — deeper range than a barbell allows." },
  { id: "incline-db-press", name: "Incline dumbbell press", muscle: "chest", secondary: ["shoulders", "triceps"], equipment: "dumbbell", difficulty: "beginner", instructions: "On an incline bench, press dumbbells up and slightly together.", tip: "Keep elbows about 45° from your torso." },
  { id: "db-fly", name: "Dumbbell fly", muscle: "chest", secondary: [], equipment: "dumbbell", difficulty: "intermediate", instructions: "With a slight elbow bend, open your arms wide and squeeze back together over your chest.", tip: "Think of hugging a barrel — don't turn it into a press." },
  { id: "cable-crossover", name: "Cable crossover", muscle: "chest", secondary: [], equipment: "cable", difficulty: "beginner", instructions: "From high pulleys, bring handles down and together in front of your chest.", tip: "Pause and squeeze for a second at the midpoint." },
  { id: "push-up", name: "Push-up", muscle: "chest", secondary: ["triceps", "core"], equipment: "bodyweight", difficulty: "beginner", instructions: "Hands under shoulders, body in a straight line, lower chest to the floor and press up.", tip: "Squeeze your glutes to keep your hips from sagging." },
  { id: "machine-chest-press", name: "Machine chest press", muscle: "chest", secondary: ["triceps"], equipment: "machine", difficulty: "beginner", instructions: "Adjust the seat so handles sit at mid-chest, press to lockout.", tip: "Control the negative — two seconds down." },
  { id: "pec-deck", name: "Pec deck", muscle: "chest", secondary: [], equipment: "machine", difficulty: "beginner", instructions: "With forearms or hands on the pads, bring the arms together in front of you.", tip: "Set the seat so your elbows match shoulder height." },

  // Back (11)
  { id: "deadlift", name: "Deadlift", muscle: "back", secondary: ["hamstrings", "glutes", "forearms"], equipment: "barbell", difficulty: "advanced", instructions: "Hinge down, grip the bar outside your knees, brace, and stand up by driving through the floor.", tip: "The bar should stay in contact with your legs the whole way." },
  { id: "pull-up", name: "Pull-up", muscle: "back", secondary: ["biceps"], equipment: "bodyweight", difficulty: "intermediate", instructions: "Overhand grip, pull your chin over the bar, lower under control.", tip: "Lead with your chest, not your chin." },
  { id: "chin-up", name: "Chin-up", muscle: "back", secondary: ["biceps"], equipment: "bodyweight", difficulty: "intermediate", instructions: "Underhand grip, pull until your chin clears the bar.", tip: "Full hang at the bottom — no half reps." },
  { id: "lat-pulldown", name: "Lat pulldown", muscle: "back", secondary: ["biceps"], equipment: "cable", difficulty: "beginner", instructions: "Pull the bar to your upper chest while leaning back slightly.", tip: "Drive your elbows down and back, don't pull with your hands." },
  { id: "barbell-row", name: "Barbell row", muscle: "back", secondary: ["biceps", "core"], equipment: "barbell", difficulty: "intermediate", instructions: "Hinge to about 45°, row the bar to your lower ribs.", tip: "If you have to heave with your hips, it's too heavy." },
  { id: "db-row", name: "Dumbbell row", muscle: "back", secondary: ["biceps"], equipment: "dumbbell", difficulty: "beginner", instructions: "One hand on the bench, row the dumbbell to your hip.", tip: "Pull with your elbow, keep your torso square." },
  { id: "cable-row", name: "Seated cable row", muscle: "back", secondary: ["biceps"], equipment: "cable", difficulty: "beginner", instructions: "Sit tall, pull the handle to your stomach, squeeze your shoulder blades.", tip: "Don't rock — your torso stays nearly vertical." },
  { id: "t-bar-row", name: "T-bar row", muscle: "back", secondary: ["biceps"], equipment: "barbell", difficulty: "intermediate", instructions: "Straddle the bar, hinge forward, row the handles to your chest.", tip: "Keep your chest up against the pad if using one." },
  { id: "straight-arm-pulldown", name: "Straight-arm pulldown", muscle: "back", secondary: ["core"], equipment: "cable", difficulty: "beginner", instructions: "Arms nearly straight, pull the bar from eye level down to your thighs.", tip: "Feel it in your lats, not your triceps." },
  { id: "rack-pull", name: "Rack pull", muscle: "back", secondary: ["glutes", "forearms"], equipment: "barbell", difficulty: "intermediate", instructions: "Deadlift from knee-height pins — brace and stand tall.", tip: "Squeeze your glutes hard at lockout, don't lean back." },
  { id: "back-extension", name: "Back extension", muscle: "back", secondary: ["glutes", "hamstrings"], equipment: "bodyweight", difficulty: "beginner", instructions: "Hinge over the pad and raise your torso until your body is straight.", tip: "Don't hyperextend at the top." },

  // Shoulders (9)
  { id: "ohp", name: "Overhead press", muscle: "shoulders", secondary: ["triceps", "core"], equipment: "barbell", difficulty: "intermediate", instructions: "From the front rack, press the bar overhead until your elbows lock.", tip: "Squeeze your glutes so your lower back doesn't arch." },
  { id: "db-shoulder-press", name: "Seated dumbbell press", muscle: "shoulders", secondary: ["triceps"], equipment: "dumbbell", difficulty: "beginner", instructions: "Seated with back support, press dumbbells from ear level to overhead.", tip: "Lower until your elbows hit about 90°." },
  { id: "arnold-press", name: "Arnold press", muscle: "shoulders", secondary: ["triceps"], equipment: "dumbbell", difficulty: "intermediate", instructions: "Start palms facing you, rotate out as you press overhead.", tip: "Keep the rotation smooth — no jerking." },
  { id: "lateral-raise", name: "Lateral raise", muscle: "shoulders", secondary: [], equipment: "dumbbell", difficulty: "beginner", instructions: "Raise dumbbells out to your sides to shoulder height.", tip: "Lead with your elbows; tilt the pinky slightly up." },
  { id: "cable-lateral-raise", name: "Cable lateral raise", muscle: "shoulders", secondary: [], equipment: "cable", difficulty: "beginner", instructions: "With the cable behind your body, raise your arm out to the side.", tip: "Constant tension — don't rest at the bottom." },
  { id: "front-raise", name: "Front raise", muscle: "shoulders", secondary: [], equipment: "dumbbell", difficulty: "beginner", instructions: "Raise the dumbbell in front of you to shoulder height.", tip: "No swinging — strict and controlled." },
  { id: "rear-delt-fly", name: "Rear delt fly", muscle: "shoulders", secondary: ["back"], equipment: "dumbbell", difficulty: "beginner", instructions: "Hinged forward, open your arms out wide behind you.", tip: "Think about pulling the dumbbells apart, not lifting them." },
  { id: "face-pull", name: "Face pull", muscle: "shoulders", secondary: ["back"], equipment: "cable", difficulty: "beginner", instructions: "Pull the rope toward your face, ending with hands beside your ears.", tip: "External rotation at the end is the whole point." },
  { id: "upright-row", name: "Upright row", muscle: "shoulders", secondary: ["biceps"], equipment: "barbell", difficulty: "intermediate", instructions: "Pull the bar up your body to chest height, elbows leading.", tip: "Stop at chest height — higher can pinch the shoulder." },

  // Biceps (6)
  { id: "barbell-curl", name: "Barbell curl", muscle: "biceps", secondary: ["forearms"], equipment: "barbell", difficulty: "beginner", instructions: "Curl the bar from your thighs to shoulder height without swinging.", tip: "Pin your elbows to your sides." },
  { id: "db-curl", name: "Dumbbell curl", muscle: "biceps", secondary: ["forearms"], equipment: "dumbbell", difficulty: "beginner", instructions: "Curl with palms up, one or both arms.", tip: "Full extension at the bottom of every rep." },
  { id: "hammer-curl", name: "Hammer curl", muscle: "biceps", secondary: ["forearms"], equipment: "dumbbell", difficulty: "beginner", instructions: "Curl with palms facing each other.", tip: "Hits the brachialis — great for arm thickness." },
  { id: "incline-db-curl", name: "Incline dumbbell curl", muscle: "biceps", secondary: [], equipment: "dumbbell", difficulty: "intermediate", instructions: "Seated on an incline bench, let your arms hang back and curl.", tip: "The stretch at the bottom is where the value is." },
  { id: "preacher-curl", name: "Preacher curl", muscle: "biceps", secondary: [], equipment: "barbell", difficulty: "beginner", instructions: "With arms on the preacher pad, curl the bar up.", tip: "Don't fully lock out at the bottom under heavy load." },
  { id: "cable-curl", name: "Cable curl", muscle: "biceps", secondary: ["forearms"], equipment: "cable", difficulty: "beginner", instructions: "Curl the bar from a low pulley.", tip: "Constant tension — squeeze hard at the top." },

  // Triceps (6)
  { id: "close-grip-bench", name: "Close-grip bench press", muscle: "triceps", secondary: ["chest", "shoulders"], equipment: "barbell", difficulty: "intermediate", instructions: "Bench press with hands shoulder-width, elbows tucked.", tip: "Touch lower on your chest than a normal bench." },
  { id: "skull-crusher", name: "Skull crusher", muscle: "triceps", secondary: [], equipment: "barbell", difficulty: "intermediate", instructions: "Lying down, lower the bar to your forehead by bending the elbows, then extend.", tip: "Let the bar drift slightly behind your head to keep tension." },
  { id: "pushdown", name: "Cable pushdown", muscle: "triceps", secondary: [], equipment: "cable", difficulty: "beginner", instructions: "Elbows pinned, push the bar or rope down to lockout.", tip: "If your elbows flare forward, drop the weight." },
  { id: "overhead-extension", name: "Overhead cable extension", muscle: "triceps", secondary: [], equipment: "cable", difficulty: "beginner", instructions: "Facing away from the pulley, extend your arms overhead.", tip: "The long head only gets stretched overhead — don't skip this." },
  { id: "dip", name: "Dip", muscle: "triceps", secondary: ["chest", "shoulders"], equipment: "bodyweight", difficulty: "intermediate", instructions: "On parallel bars, lower until your upper arms are parallel, press up.", tip: "Stay upright for triceps, lean forward for chest." },
  { id: "diamond-push-up", name: "Diamond push-up", muscle: "triceps", secondary: ["chest"], equipment: "bodyweight", difficulty: "intermediate", instructions: "Push-up with hands together under your chest forming a diamond.", tip: "Keep your elbows tracking back, not out." },

  // Forearms (2)
  { id: "wrist-curl", name: "Wrist curl", muscle: "forearms", secondary: [], equipment: "dumbbell", difficulty: "beginner", instructions: "Forearms on your thighs, curl the weight with just your wrists.", tip: "High reps work best — 15 to 20." },
  { id: "farmers-carry", name: "Farmer's carry", muscle: "forearms", secondary: ["core", "full body"], equipment: "dumbbell", difficulty: "beginner", instructions: "Carry heavy dumbbells at your sides for distance or time.", tip: "Walk tall — shoulders back, core braced." },

  // Core (7)
  { id: "plank", name: "Plank", muscle: "core", secondary: [], equipment: "bodyweight", difficulty: "beginner", instructions: "Hold a straight line from head to heels on your forearms.", tip: "Squeeze glutes and abs — don't just hang on your spine." },
  { id: "crunch", name: "Crunch", muscle: "core", secondary: [], equipment: "bodyweight", difficulty: "beginner", instructions: "Curl your shoulder blades off the floor and lower slowly.", tip: "Exhale hard at the top of each rep." },
  { id: "hanging-leg-raise", name: "Hanging leg raise", muscle: "core", secondary: ["forearms"], equipment: "bodyweight", difficulty: "advanced", instructions: "Hanging from a bar, raise your legs to hip height or above.", tip: "Tilt your pelvis up at the top — that's the ab part." },
  { id: "cable-crunch", name: "Cable crunch", muscle: "core", secondary: [], equipment: "cable", difficulty: "beginner", instructions: "Kneeling below a high pulley, crunch your elbows toward your knees.", tip: "Flex your spine — don't just bow at the hips." },
  { id: "russian-twist", name: "Russian twist", muscle: "core", secondary: [], equipment: "bodyweight", difficulty: "beginner", instructions: "Seated and leaned back, rotate your torso side to side.", tip: "Slower is harder and better." },
  { id: "ab-wheel", name: "Ab wheel rollout", muscle: "core", secondary: ["shoulders"], equipment: "bodyweight", difficulty: "advanced", instructions: "From your knees, roll the wheel forward as far as you can control, then pull back.", tip: "If your back arches, shorten the range." },
  { id: "side-plank", name: "Side plank", muscle: "core", secondary: [], equipment: "bodyweight", difficulty: "beginner", instructions: "Hold a straight line on one forearm, hips stacked.", tip: "Push the floor away — don't sink into the shoulder." },

  // Quads (8)
  { id: "squat", name: "Back squat", muscle: "quads", secondary: ["glutes", "core", "hamstrings"], equipment: "barbell", difficulty: "advanced", instructions: "Bar on your upper back, sit down between your hips until your thighs pass parallel, stand up.", tip: "Drive your knees out in line with your toes." },
  { id: "front-squat", name: "Front squat", muscle: "quads", secondary: ["glutes", "core"], equipment: "barbell", difficulty: "advanced", instructions: "Bar racked on your front delts, squat keeping your torso vertical.", tip: "Elbows high the whole rep or the bar rolls forward." },
  { id: "leg-press", name: "Leg press", muscle: "quads", secondary: ["glutes"], equipment: "machine", difficulty: "beginner", instructions: "Lower the sled until your knees near your chest, press back up.", tip: "Don't let your lower back peel off the pad." },
  { id: "hack-squat", name: "Hack squat", muscle: "quads", secondary: ["glutes"], equipment: "machine", difficulty: "intermediate", instructions: "Squat on the angled sled, back flat against the pad.", tip: "Go deep — the machine keeps you safe." },
  { id: "bulgarian-split-squat", name: "Bulgarian split squat", muscle: "quads", secondary: ["glutes"], equipment: "dumbbell", difficulty: "intermediate", instructions: "Rear foot on a bench, lower your back knee toward the floor.", tip: "Slight forward lean shifts it to glutes; upright hits quads." },
  { id: "walking-lunge", name: "Walking lunge", muscle: "quads", secondary: ["glutes", "core"], equipment: "dumbbell", difficulty: "beginner", instructions: "Step forward into a lunge, push through the front heel, repeat.", tip: "Long steps for glutes, short steps for quads." },
  { id: "leg-extension", name: "Leg extension", muscle: "quads", secondary: [], equipment: "machine", difficulty: "beginner", instructions: "Extend your knees against the pad to full lockout.", tip: "Pause one second at the top." },
  { id: "goblet-squat", name: "Goblet squat", muscle: "quads", secondary: ["glutes", "core"], equipment: "dumbbell", difficulty: "beginner", instructions: "Hold a dumbbell at your chest, squat deep between your knees.", tip: "The counterweight makes depth easy — use it." },

  // Hamstrings (5)
  { id: "rdl", name: "Romanian deadlift", muscle: "hamstrings", secondary: ["glutes", "back"], equipment: "barbell", difficulty: "intermediate", instructions: "Soft knees, push your hips back letting the bar slide down your thighs, then drive hips forward.", tip: "It ends where your hamstrings run out of stretch — not at the floor." },
  { id: "lying-leg-curl", name: "Lying leg curl", muscle: "hamstrings", secondary: [], equipment: "machine", difficulty: "beginner", instructions: "Face down, curl the pad to your glutes.", tip: "Keep your hips pressed into the bench." },
  { id: "seated-leg-curl", name: "Seated leg curl", muscle: "hamstrings", secondary: [], equipment: "machine", difficulty: "beginner", instructions: "Curl the pad under the seat, squeeze at the bottom.", tip: "Better stretch than lying curls — lean slightly forward." },
  { id: "good-morning", name: "Good morning", muscle: "hamstrings", secondary: ["back", "glutes"], equipment: "barbell", difficulty: "advanced", instructions: "Bar on your back, hinge forward until your torso nears parallel, stand up.", tip: "Start light. This one punishes ego." },
  { id: "nordic-curl", name: "Nordic curl", muscle: "hamstrings", secondary: [], equipment: "bodyweight", difficulty: "advanced", instructions: "Knees anchored, lower your body forward under control, push back up.", tip: "Use your hands to catch and assist — almost no one does these unassisted." },

  // Glutes (4)
  { id: "hip-thrust", name: "Hip thrust", muscle: "glutes", secondary: ["hamstrings"], equipment: "barbell", difficulty: "intermediate", instructions: "Upper back on a bench, drive the bar up with your hips to full extension.", tip: "Chin tucked, ribs down at the top — no back arching." },
  { id: "glute-bridge", name: "Glute bridge", muscle: "glutes", secondary: ["hamstrings"], equipment: "bodyweight", difficulty: "beginner", instructions: "On your back, knees bent, drive your hips to the ceiling.", tip: "Pause and squeeze for two seconds at the top." },
  { id: "cable-kickback", name: "Cable kickback", muscle: "glutes", secondary: [], equipment: "cable", difficulty: "beginner", instructions: "Ankle strap on, kick your leg back and slightly up.", tip: "Squeeze the glute, don't swing from your back." },
  { id: "sumo-deadlift", name: "Sumo deadlift", muscle: "glutes", secondary: ["hamstrings", "back", "quads"], equipment: "barbell", difficulty: "advanced", instructions: "Wide stance, grip inside your knees, wedge down and stand up.", tip: "Open your knees out over your toes before you pull." },

  // Calves (3)
  { id: "standing-calf-raise", name: "Standing calf raise", muscle: "calves", secondary: [], equipment: "machine", difficulty: "beginner", instructions: "Rise onto your toes as high as possible, lower until you feel a deep stretch.", tip: "Two-second pause at the bottom kills the bounce." },
  { id: "seated-calf-raise", name: "Seated calf raise", muscle: "calves", secondary: [], equipment: "machine", difficulty: "beginner", instructions: "Knees bent under the pad, raise and lower your heels.", tip: "Seated hits the soleus — both versions matter." },
  { id: "donkey-calf-raise", name: "Donkey calf raise", muscle: "calves", secondary: [], equipment: "machine", difficulty: "intermediate", instructions: "Hinged forward, raise your heels with weight over your hips.", tip: "The stretch in this position is the best of any calf lift." },

  // Full body (1)
  { id: "kb-swing", name: "Kettlebell swing", muscle: "full body", secondary: ["glutes", "hamstrings", "core"], equipment: "kettlebell", difficulty: "intermediate", instructions: "Hinge and snap your hips to swing the bell to chest height.", tip: "It's a hip hinge, not a squat — the arms are just hooks." },

  // ── Expanded library ──────────────────────────────────────────────────────

  // Chest (more)
  { id: "decline-bench", name: "Decline barbell press", muscle: "chest", secondary: ["triceps"], equipment: "barbell", difficulty: "intermediate", instructions: "On a decline bench, lower the bar to your lower chest and press up.", tip: "Targets the lower chest — keep the bar path over the nipple line." },
  { id: "decline-db-press", name: "Decline dumbbell press", muscle: "chest", secondary: ["triceps"], equipment: "dumbbell", difficulty: "beginner", instructions: "On a decline bench, press dumbbells from your lower chest to lockout.", tip: "Have a partner hand you the dumbbells in this position." },
  { id: "floor-press", name: "Floor press", muscle: "chest", secondary: ["triceps"], equipment: "barbell", difficulty: "intermediate", instructions: "Lying on the floor, press the bar from a dead stop at the bottom.", tip: "Triceps-heavy — the floor stops your elbows shy of full stretch." },
  { id: "db-pullover", name: "Dumbbell pullover", muscle: "chest", secondary: ["back"], equipment: "dumbbell", difficulty: "intermediate", instructions: "Lying across a bench, lower one dumbbell behind your head and pull it back over your chest.", tip: "Keep a slight elbow bend and feel the rib-cage stretch." },
  { id: "incline-cable-fly", name: "Incline cable fly", muscle: "chest", secondary: [], equipment: "cable", difficulty: "beginner", instructions: "On an incline bench between two pulleys, bring the handles together above your chest.", tip: "Constant tension beats dumbbells at the top of the rep." },
  { id: "low-to-high-fly", name: "Low-to-high cable fly", muscle: "chest", secondary: [], equipment: "cable", difficulty: "beginner", instructions: "From low pulleys, sweep the handles up and together at chin height.", tip: "Hits the upper chest fibers — squeeze up high." },
  { id: "high-to-low-fly", name: "High-to-low cable fly", muscle: "chest", secondary: [], equipment: "cable", difficulty: "beginner", instructions: "From high pulleys, bring the handles down and together at your hips.", tip: "Emphasizes the lower/inner chest." },
  { id: "chest-dip", name: "Chest dip", muscle: "chest", secondary: ["triceps", "shoulders"], equipment: "bodyweight", difficulty: "intermediate", instructions: "On parallel bars, lean forward and lower deep, then press up.", tip: "The forward lean is what shifts it from triceps to chest." },
  { id: "smith-bench-press", name: "Smith machine bench press", muscle: "chest", secondary: ["triceps", "shoulders"], equipment: "machine", difficulty: "beginner", instructions: "Press the fixed bar from mid-chest to lockout.", tip: "The fixed path lets you push closer to failure safely." },
  { id: "machine-incline-press", name: "Machine incline press", muscle: "chest", secondary: ["shoulders", "triceps"], equipment: "machine", difficulty: "beginner", instructions: "Set the seat low and press the handles up and slightly together.", tip: "Great for chasing the upper chest with no stabilizer fatigue." },
  { id: "landmine-press", name: "Landmine press", muscle: "chest", secondary: ["shoulders", "triceps"], equipment: "barbell", difficulty: "beginner", instructions: "With one end of a barbell anchored, press the other up and forward.", tip: "Shoulder-friendly pressing angle — good for cranky shoulders." },
  { id: "svend-press", name: "Svend press", muscle: "chest", secondary: [], equipment: "dumbbell", difficulty: "beginner", instructions: "Press a plate or dumbbell straight out from your chest, squeezing it.", tip: "All about the squeeze — keep tension the whole set." },

  // Back (more)
  { id: "chest-supported-row", name: "Chest-supported row", muscle: "back", secondary: ["biceps"], equipment: "machine", difficulty: "beginner", instructions: "Chest against the pad, row the handles to your ribs.", tip: "Removes the lower back, so you can chase your back hard." },
  { id: "pendlay-row", name: "Pendlay row", muscle: "back", secondary: ["biceps", "core"], equipment: "barbell", difficulty: "advanced", instructions: "From a dead stop on the floor, explosively row the bar to your chest each rep.", tip: "Reset on the floor between reps — strict and powerful." },
  { id: "meadows-row", name: "Meadows row", muscle: "back", secondary: ["biceps"], equipment: "barbell", difficulty: "intermediate", instructions: "Stand perpendicular to a landmine, row the end with one arm.", tip: "Great lat stretch at the bottom — let the shoulder travel." },
  { id: "seal-row", name: "Seal row", muscle: "back", secondary: ["biceps"], equipment: "dumbbell", difficulty: "intermediate", instructions: "Face-down on a raised bench, row dumbbells straight up.", tip: "Zero momentum possible — pure upper-back work." },
  { id: "wide-grip-pulldown", name: "Wide-grip pulldown", muscle: "back", secondary: ["biceps"], equipment: "cable", difficulty: "beginner", instructions: "With a wide overhand grip, pull the bar to your upper chest.", tip: "Width emphasis — think about your lats, not your arms." },
  { id: "neutral-grip-pulldown", name: "Neutral-grip pulldown", muscle: "back", secondary: ["biceps"], equipment: "cable", difficulty: "beginner", instructions: "With palms facing each other, pull the handle to your chest.", tip: "The strongest pulldown position — load it up." },
  { id: "single-arm-pulldown", name: "Single-arm lat pulldown", muscle: "back", secondary: ["biceps"], equipment: "cable", difficulty: "beginner", instructions: "With one handle, pull down and slightly back, owning the stretch.", tip: "Lets you fix a side-to-side imbalance." },
  { id: "inverted-row", name: "Inverted row", muscle: "back", secondary: ["biceps"], equipment: "bodyweight", difficulty: "beginner", instructions: "Under a fixed bar, body straight, pull your chest to the bar.", tip: "Raise your feet to make it harder, bend your knees to make it easier." },
  { id: "trap-bar-deadlift", name: "Trap bar deadlift", muscle: "back", secondary: ["quads", "glutes", "forearms"], equipment: "barbell", difficulty: "intermediate", instructions: "Stand inside the trap bar, grip the handles, and stand tall.", tip: "More forgiving on the lower back than a straight bar." },
  { id: "snatch-grip-deadlift", name: "Snatch-grip deadlift", muscle: "back", secondary: ["hamstrings", "glutes"], equipment: "barbell", difficulty: "advanced", instructions: "Deadlift with a very wide grip, extra upper-back demand.", tip: "Brutal on the traps and grip — start lighter than your normal pull." },
  { id: "barbell-shrug", name: "Barbell shrug", muscle: "back", secondary: ["forearms"], equipment: "barbell", difficulty: "beginner", instructions: "Hold the bar at your thighs and shrug your shoulders straight up.", tip: "Up and slightly back — don't roll the shoulders." },
  { id: "dumbbell-shrug", name: "Dumbbell shrug", muscle: "back", secondary: ["forearms"], equipment: "dumbbell", difficulty: "beginner", instructions: "Dumbbells at your sides, shrug your traps up and hold.", tip: "Pause hard at the top of every rep." },
  { id: "machine-row", name: "Machine row", muscle: "back", secondary: ["biceps"], equipment: "machine", difficulty: "beginner", instructions: "Chest on the pad, drive the handles back and squeeze.", tip: "Pull with the elbows; let the shoulder blades move." },
  { id: "kroc-row", name: "Kroc row", muscle: "back", secondary: ["biceps", "forearms"], equipment: "dumbbell", difficulty: "intermediate", instructions: "Heavy, slightly loose one-arm dumbbell row for high reps.", tip: "A little body english is allowed — this one's about overload." },

  // Shoulders (more)
  { id: "machine-shoulder-press", name: "Machine shoulder press", muscle: "shoulders", secondary: ["triceps"], equipment: "machine", difficulty: "beginner", instructions: "Press the handles overhead from shoulder height.", tip: "Set the seat so the handles start at ear level." },
  { id: "push-press", name: "Push press", muscle: "shoulders", secondary: ["triceps", "quads"], equipment: "barbell", difficulty: "intermediate", instructions: "Dip with the legs and drive the bar overhead, using the leg drive.", tip: "The dip is shallow and fast — all in the legs, not the arms." },
  { id: "z-press", name: "Z press", muscle: "shoulders", secondary: ["triceps", "core"], equipment: "barbell", difficulty: "advanced", instructions: "Seated on the floor with legs straight, press the bar overhead.", tip: "No leg or back help at all — humbling and great for posture." },
  { id: "reverse-pec-deck", name: "Reverse pec deck", muscle: "shoulders", secondary: ["back"], equipment: "machine", difficulty: "beginner", instructions: "Facing the pad, open your arms back in a wide arc for rear delts.", tip: "Lead with the pinkies, squeeze the rear delts." },
  { id: "cable-rear-delt-fly", name: "Cable rear delt fly", muscle: "shoulders", secondary: ["back"], equipment: "cable", difficulty: "beginner", instructions: "Cross the cables and pull your arms apart and back.", tip: "Constant tension makes this better than the dumbbell version." },
  { id: "seated-lateral-raise", name: "Seated lateral raise", muscle: "shoulders", secondary: [], equipment: "dumbbell", difficulty: "beginner", instructions: "Seated upright, raise dumbbells out to shoulder height.", tip: "Seating kills the swing — strict side delts only." },
  { id: "leaning-cable-lateral", name: "Leaning cable lateral raise", muscle: "shoulders", secondary: [], equipment: "cable", difficulty: "intermediate", instructions: "Lean away from the pulley and raise your arm out to the side.", tip: "Leaning lengthens the range — best side-delt stimulus there is." },
  { id: "cable-front-raise", name: "Cable front raise", muscle: "shoulders", secondary: [], equipment: "cable", difficulty: "beginner", instructions: "From a low pulley behind you, raise the handle to eye level.", tip: "Keep tension at the bottom — no resting." },
  { id: "smith-ohp", name: "Smith machine shoulder press", muscle: "shoulders", secondary: ["triceps"], equipment: "machine", difficulty: "beginner", instructions: "Press the fixed bar overhead from shoulder height.", tip: "Stable path lets you grind the last reps safely." },

  // Biceps (more)
  { id: "ez-bar-curl", name: "EZ-bar curl", muscle: "biceps", secondary: ["forearms"], equipment: "barbell", difficulty: "beginner", instructions: "Curl the EZ bar with a semi-supinated grip.", tip: "Easier on the wrists than a straight bar." },
  { id: "concentration-curl", name: "Concentration curl", muscle: "biceps", secondary: [], equipment: "dumbbell", difficulty: "beginner", instructions: "Seated, elbow braced on your thigh, curl one dumbbell.", tip: "The braced elbow makes cheating impossible — peak squeeze." },
  { id: "spider-curl", name: "Spider curl", muscle: "biceps", secondary: [], equipment: "dumbbell", difficulty: "intermediate", instructions: "Chest on an incline bench, arms hanging straight down, curl up.", tip: "Maximum tension in the shortened, contracted position." },
  { id: "bayesian-curl", name: "Bayesian cable curl", muscle: "biceps", secondary: [], equipment: "cable", difficulty: "intermediate", instructions: "Facing away from a low pulley, arm back, curl with a deep stretch.", tip: "The behind-the-body stretch is the whole point." },
  { id: "reverse-curl", name: "Reverse curl", muscle: "biceps", secondary: ["forearms"], equipment: "barbell", difficulty: "beginner", instructions: "Curl with an overhand grip to hit the brachialis and forearms.", tip: "Go lighter than a normal curl — the grip is the limiter." },
  { id: "machine-curl", name: "Machine preacher curl", muscle: "biceps", secondary: [], equipment: "machine", difficulty: "beginner", instructions: "Arms on the pad, curl the handles up and squeeze.", tip: "Great for drop sets — no balance needed." },

  // Triceps (more)
  { id: "rope-pushdown", name: "Rope pushdown", muscle: "triceps", secondary: [], equipment: "cable", difficulty: "beginner", instructions: "Push the rope down and split the ends apart at the bottom.", tip: "The spread at lockout is where the long head fires." },
  { id: "single-arm-pushdown", name: "Single-arm pushdown", muscle: "triceps", secondary: [], equipment: "cable", difficulty: "beginner", instructions: "With a single handle and a reverse grip, push down to lockout.", tip: "Fixes side-to-side triceps imbalances." },
  { id: "db-overhead-extension", name: "Dumbbell overhead extension", muscle: "triceps", secondary: [], equipment: "dumbbell", difficulty: "beginner", instructions: "Hold one dumbbell overhead with both hands, lower behind your head, extend.", tip: "Overhead stretches the long head — keep elbows tight." },
  { id: "bench-dip", name: "Bench dip", muscle: "triceps", secondary: ["shoulders"], equipment: "bodyweight", difficulty: "beginner", instructions: "Hands on a bench behind you, lower your hips and press back up.", tip: "Add a plate on your lap when bodyweight gets easy." },
  { id: "jm-press", name: "JM press", muscle: "triceps", secondary: ["chest"], equipment: "barbell", difficulty: "advanced", instructions: "A hybrid of a close-grip bench and skull crusher to the upper chest/neck.", tip: "Start very light — the groove takes practice." },
  { id: "tricep-kickback", name: "Tricep kickback", muscle: "triceps", secondary: [], equipment: "dumbbell", difficulty: "beginner", instructions: "Hinged forward, extend the dumbbell straight back to lockout.", tip: "Squeeze at full extension — the top is the work." },

  // Forearms (more)
  { id: "reverse-wrist-curl", name: "Reverse wrist curl", muscle: "forearms", secondary: [], equipment: "dumbbell", difficulty: "beginner", instructions: "Forearms on your thighs, palms down, lift the weight with your wrists.", tip: "Light weight, high reps — extensors are small." },
  { id: "wrist-roller", name: "Wrist roller", muscle: "forearms", secondary: [], equipment: "cable", difficulty: "intermediate", instructions: "Roll a weight up on a cord by rotating the bar, then lower it slowly.", tip: "The lowering phase is where the burn lives." },
  { id: "dead-hang", name: "Dead hang", muscle: "forearms", secondary: ["back"], equipment: "bodyweight", difficulty: "beginner", instructions: "Hang from a bar for time with a full grip.", tip: "Builds grip and decompresses the spine — go for time." },
  { id: "plate-pinch", name: "Plate pinch", muscle: "forearms", secondary: [], equipment: "bodyweight", difficulty: "beginner", instructions: "Pinch two plates together smooth-side out and hold for time.", tip: "Trains the thumb and pinch grip nothing else hits." },

  // Core (more)
  { id: "v-up", name: "V-up", muscle: "core", secondary: [], equipment: "bodyweight", difficulty: "intermediate", instructions: "Lying flat, simultaneously raise your legs and torso to touch over your hips.", tip: "Move slowly — speed makes it momentum, not abs." },
  { id: "bicycle-crunch", name: "Bicycle crunch", muscle: "core", secondary: [], equipment: "bodyweight", difficulty: "beginner", instructions: "Alternate bringing each elbow to the opposite knee.", tip: "Rotate from the torso, not just the elbows." },
  { id: "dead-bug", name: "Dead bug", muscle: "core", secondary: [], equipment: "bodyweight", difficulty: "beginner", instructions: "On your back, extend opposite arm and leg while keeping your back flat.", tip: "If your lower back lifts, shorten the reach." },
  { id: "pallof-press", name: "Pallof press", muscle: "core", secondary: [], equipment: "cable", difficulty: "beginner", instructions: "Side-on to a cable, press the handle straight out and resist the twist.", tip: "Anti-rotation — the goal is to not move." },
  { id: "toes-to-bar", name: "Toes to bar", muscle: "core", secondary: ["forearms"], equipment: "bodyweight", difficulty: "advanced", instructions: "Hanging from a bar, raise your toes all the way up to touch it.", tip: "Control the swing down — no kipping for ab work." },
  { id: "hollow-hold", name: "Hollow body hold", muscle: "core", secondary: [], equipment: "bodyweight", difficulty: "intermediate", instructions: "On your back, press your lower back down and hold arms and legs off the floor.", tip: "Lower-back glued to the floor the whole time." },
  { id: "decline-sit-up", name: "Decline sit-up", muscle: "core", secondary: [], equipment: "bodyweight", difficulty: "beginner", instructions: "On a decline bench, sit all the way up under control.", tip: "Hold a plate on your chest to add load." },

  // Quads (more)
  { id: "smith-squat", name: "Smith machine squat", muscle: "quads", secondary: ["glutes"], equipment: "machine", difficulty: "beginner", instructions: "With feet slightly forward, squat on the fixed bar.", tip: "Feet forward shifts more load onto the quads." },
  { id: "pause-squat", name: "Pause squat", muscle: "quads", secondary: ["glutes", "core"], equipment: "barbell", difficulty: "advanced", instructions: "Back squat with a 2–3 second pause at the bottom.", tip: "Kills the bounce and builds strength out of the hole." },
  { id: "sissy-squat", name: "Sissy squat", muscle: "quads", secondary: [], equipment: "bodyweight", difficulty: "advanced", instructions: "Lean back on your toes and bend at the knees, hips locked straight.", tip: "Intense quad and knee-extension stretch — ease in." },
  { id: "step-up", name: "Step-up", muscle: "quads", secondary: ["glutes"], equipment: "dumbbell", difficulty: "beginner", instructions: "Step up onto a box driving through the lead heel, control the way down.", tip: "Don't push off the trailing foot — make the top leg work." },
  { id: "reverse-lunge", name: "Reverse lunge", muscle: "quads", secondary: ["glutes"], equipment: "dumbbell", difficulty: "beginner", instructions: "Step backward into a lunge and drive back up through the front leg.", tip: "Easier on the knees than forward lunges." },
  { id: "belt-squat", name: "Belt squat", muscle: "quads", secondary: ["glutes"], equipment: "machine", difficulty: "beginner", instructions: "With the load hanging from a hip belt, squat down and up.", tip: "Zero spinal load — great when your back is fried." },

  // Hamstrings (more)
  { id: "stiff-leg-deadlift", name: "Stiff-leg deadlift", muscle: "hamstrings", secondary: ["glutes", "back"], equipment: "barbell", difficulty: "intermediate", instructions: "With near-straight legs, hinge and lower the bar down your shins.", tip: "Even bigger stretch than an RDL — keep the bar close." },
  { id: "single-leg-rdl", name: "Single-leg RDL", muscle: "hamstrings", secondary: ["glutes", "core"], equipment: "dumbbell", difficulty: "intermediate", instructions: "On one leg, hinge forward reaching the dumbbell toward the floor.", tip: "Square your hips to the ground — don't let them open." },
  { id: "db-rdl", name: "Dumbbell Romanian deadlift", muscle: "hamstrings", secondary: ["glutes", "back"], equipment: "dumbbell", difficulty: "beginner", instructions: "Hinge at the hips, lowering the dumbbells down your thighs.", tip: "The stretch, not the floor, ends the rep." },
  { id: "glute-ham-raise", name: "Glute-ham raise", muscle: "hamstrings", secondary: ["glutes"], equipment: "bodyweight", difficulty: "advanced", instructions: "Anchored at the ankles on a GHD, lower and raise your torso under control.", tip: "Brutal — assist with a push off the floor at first." },
  { id: "cable-pull-through", name: "Cable pull-through", muscle: "hamstrings", secondary: ["glutes"], equipment: "cable", difficulty: "beginner", instructions: "Face away from a low pulley, hinge and drive your hips forward.", tip: "Power comes from the hips snapping through, not the arms." },

  // Glutes (more)
  { id: "db-hip-thrust", name: "Dumbbell hip thrust", muscle: "glutes", secondary: ["hamstrings"], equipment: "dumbbell", difficulty: "beginner", instructions: "Upper back on a bench, drive a dumbbell up with your hips.", tip: "A good entry before you load a barbell across your hips." },
  { id: "single-leg-hip-thrust", name: "Single-leg hip thrust", muscle: "glutes", secondary: ["hamstrings"], equipment: "bodyweight", difficulty: "intermediate", instructions: "One foot planted, drive your hips up on a single leg.", tip: "Evens out a strong/weak side." },
  { id: "hip-abduction", name: "Hip abduction machine", muscle: "glutes", secondary: [], equipment: "machine", difficulty: "beginner", instructions: "Push your knees out against the pads and squeeze the glutes.", tip: "Lean forward slightly to bias the upper glutes." },
  { id: "frog-pump", name: "Frog pump", muscle: "glutes", secondary: [], equipment: "bodyweight", difficulty: "beginner", instructions: "Soles of your feet together, pump your hips up and squeeze.", tip: "High reps to finish glutes off — chase the burn." },
  { id: "curtsy-lunge", name: "Curtsy lunge", muscle: "glutes", secondary: ["quads"], equipment: "dumbbell", difficulty: "beginner", instructions: "Step one leg back and across behind the other, then drive up.", tip: "Hits the glute medius — the side-butt." },

  // Calves (more)
  { id: "leg-press-calf-raise", name: "Leg press calf raise", muscle: "calves", secondary: [], equipment: "machine", difficulty: "beginner", instructions: "On the leg press, push the sled with the balls of your feet only.", tip: "Full stretch at the bottom, full squeeze at the top." },
  { id: "single-leg-calf-raise", name: "Single-leg calf raise", muscle: "calves", secondary: [], equipment: "dumbbell", difficulty: "beginner", instructions: "On one foot holding a dumbbell, rise onto your toes and lower slowly.", tip: "Unilateral overload — most people are weaker than they think." },
  { id: "tibialis-raise", name: "Tibialis raise", muscle: "calves", secondary: [], equipment: "bodyweight", difficulty: "beginner", instructions: "Back against a wall, pull your toes up toward your shins.", tip: "Trains the front of the shin — great for knee health." },

  // Full body / Olympic (more)
  { id: "power-clean", name: "Power clean", muscle: "full body", secondary: ["back", "quads", "shoulders"], equipment: "barbell", difficulty: "advanced", instructions: "Explosively pull the bar from the floor and catch it on your front delts.", tip: "Triple extension — hips, knees, ankles snap together." },
  { id: "hang-clean", name: "Hang clean", muscle: "full body", secondary: ["back", "shoulders"], equipment: "barbell", difficulty: "advanced", instructions: "From the hang at the hip, explode and catch the bar in the front rack.", tip: "A great entry to the clean — no floor pull to coordinate." },
  { id: "thruster", name: "Thruster", muscle: "full body", secondary: ["quads", "shoulders", "triceps"], equipment: "barbell", difficulty: "intermediate", instructions: "Front squat into an overhead press in one fluid motion.", tip: "Use the drive out of the squat to launch the press." },
  { id: "push-jerk", name: "Push jerk", muscle: "full body", secondary: ["shoulders", "triceps", "quads"], equipment: "barbell", difficulty: "advanced", instructions: "Dip, drive the bar up, and drop under it with locked arms.", tip: "Re-bend the knees to receive — speed under the bar matters." },
  { id: "turkish-get-up", name: "Turkish get-up", muscle: "full body", secondary: ["core", "shoulders"], equipment: "kettlebell", difficulty: "advanced", instructions: "From lying, stand up while holding a weight locked out overhead.", tip: "Eyes on the bell the whole way up and down." },
  { id: "burpee", name: "Burpee", muscle: "full body", secondary: ["chest", "quads"], equipment: "bodyweight", difficulty: "beginner", instructions: "Drop to a push-up, jump your feet in, and jump up.", tip: "Conditioning staple — set a pace you can hold." },
];

export function getExercise(
  id: string,
  custom: Exercise[] = []
): Exercise | undefined {
  return EXERCISES.find((e) => e.id === id) ?? custom.find((e) => e.id === id);
}

export function allExercises(custom: Exercise[] = []): Exercise[] {
  return [...custom, ...EXERCISES];
}
